# docker-compose.yml
version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

